In [1]:
from sklearn import model_selection, datasets
import numpy as np

In [2]:
X = range(0, 10)

### KFold

In [3]:
kf = model_selection.KFold(n_splits=5)
for train_indices, test_indices in kf.split(X):
    print(train_indices, test_indices)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [4]:
kf = model_selection.KFold(n_splits=2, shuffle=True)
for train_indices, test_indices in kf.split(X):
    print(train_indices, test_indices)

[0 2 7 8 9] [1 3 4 5 6]
[1 3 4 5 6] [0 2 7 8 9]


In [5]:
kf = model_selection.KFold(n_splits=2, shuffle=True, random_state=1)
for train_indices, test_indices in kf.split(X):
    print(train_indices, test_indices)

[1 3 5 7 8] [0 2 4 6 9]
[0 2 4 6 9] [1 3 5 7 8]


### StratifiedKFold

In [6]:
y = np.array([0]*5 + [1]*5)
print(y)

skf = model_selection.StratifiedKFold(n_splits=2, shuffle=True, random_state=0)
for train_indices, test_indices in skf.split(X, y):
    print(train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[3 4 6 8 9] [0 1 2 5 7]
[0 1 2 5 7] [3 4 6 8 9]


In [7]:
target = np.array([0, 1] * 5)
print(target)

skf = model_selection.StratifiedKFold(n_splits=2, shuffle=True)
for train_indices, test_indices in skf.split(X, target):
    print(train_indices, test_indices)

[0 1 0 1 0 1 0 1 0 1]
[0 1 3 4 5] [2 6 7 8 9]
[2 6 7 8 9] [0 1 3 4 5]


### ShuffleSplit

In [8]:
ss = model_selection.ShuffleSplit(n_splits=10, test_size=0.2)

for train_indices, test_indices in ss.split(X):
    print(train_indices, test_indices)

[8 9 5 6 2 7 3 4] [1 0]
[6 4 5 2 1 0 8 7] [9 3]
[8 9 7 1 2 3 5 6] [0 4]
[5 2 6 4 0 7 9 1] [8 3]
[9 4 7 8 3 1 6 5] [0 2]
[5 6 9 1 0 8 2 4] [7 3]
[0 6 7 4 1 5 2 9] [8 3]
[3 1 6 8 2 9 5 7] [4 0]
[4 0 9 8 5 6 2 7] [1 3]
[6 1 3 2 7 8 0 4] [5 9]


### StratifiedShuffleSplit

In [9]:
target = np.array([0]*5 + [1]*5)
print(target)

sss = model_selection.StratifiedShuffleSplit(n_splits=4, test_size=0.2)
for train_indices, test_indices in sss.split(X, target):
    print(train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[7 1 0 8 5 3 4 6] [2 9]
[0 6 9 4 3 2 5 8] [7 1]
[6 2 3 8 4 7 9 1] [5 0]
[4 7 1 0 8 6 2 9] [5 3]


### Leave-One-Out

In [10]:
loo = model_selection.LeaveOneOut()

for train_indices, test_index in loo.split(X):
    print(train_indices, test_index)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]
